### ISSUE TITLE
Bug Report -- PROBLEMS IMPORTING LEADS TO LIST

### ISSUE THREAD

**Issue by bradleeedwards** [merchantprotocol/shadowmailer-support#33]
Issue Brief
--
When was this bug experienced: TODAY

See Loom: https://www.loom.com/share/a1778c4acaa54bde98591a16dfddf043

Resources
--

Loom: https://www.loom.com/share/a1778c4acaa54bde98591a16dfddf043

Steps to reproduce
--

1. Bug was found in the LinkedIn Database

Actual result
--

1. See Loom: https://www.loom.com/share/a1778c4acaa54bde98591a16dfddf043

Expected result
--

- Expected to see leads added to a list, but couldn't even select them except one at a time.

**Comment by alancarvalho** [comment]
Hi @snlogix 

Please take a look on this issue.

**Comment by snlogix** [comment]
> Hi @snlogix
> 
> Please take a look on this issue.

Hello @alancarvalho 
For this issue I required all the tables which is used in leads database because I'm getting this error for leads page. [https://prnt.sc/YImKXqQyz22t, https://prnt.sc/_RLY90hys4pG]

**Comment by alancarvalho** [comment]
Hi @snlogix 

That table were shared with you in another Task.
You should be able to start looking into this issue now.

Regards,

**Comment by alancarvalho** [comment]
Hi @snlogix 

Any updates on this task?

**Comment by jonathonbyrdziak** [comment]
Selecting 1000 and 5000 works. It just doesn't select them visually on the page. 

Trust that it works and they'll import fine
